stages:
  extract_data:
    cmd: python3 src/data/extract_data.py
    deps:
    - src/data/extract_data.py
    - data/raw/datasets.zip
    outs:
    - data/raw/datasets:
        cache: false
  make_dataset:
    cmd: python3 src/data/make_dataset.py
    deps:
    - data/raw/datasets
    - src/data/make_dataset.py
    outs:
    - data/processed/datasets_processed.zip:
        persist: true
  train_model:
    cmd: python3 src/models/train_model.py
    deps:
    - data/processed/datasets_processed.zip
    - src/models/train_model.py
    outs:
    - models/saved/10_50_0.001_0.25_unet_model.pth:
        persist: true
    - models/saved/10_25_0.001_0.25_unet_model.pth:
        persist: true
    - models/saved/10_50_0.1_0.25_unet_model.pth:
        persist: true
    - models/saved/10_25_0.1_0.25_unet_model.pth:
        persist: true
  predict_model:
    cmd: python3 src/models/predict_model.py
    deps:
    - models/saved/10_50_0.001_0.25_unet_model.pth
    - models/saved/10_25_0.001_0.25_unet_model.pth
    - models/saved/10_50_0.1_0.25_unet_model.pth
    - models/saved/10_25_0.1_0.25_unet_model.pth
    - src/models/predict_model.py
    outs:
    - models/saved/sd_10_50_0.001_0.25_unet_model.pth:
        persist: true
    - models/saved/sd_10_25_0.001_0.25_unet_model.pth:
        persist: true
    - models/saved/sd_10_50_0.1_0.25_unet_model.pth:
        persist: true
    - models/saved/sd_10_25_0.1_0.25_unet_model.pth:
        persist: true
    metrics:
    - models/metrics/10_50_0.001_0.25.metrics
    - models/metrics/10_25_0.001_0.25.metrics
    - models/metrics/10_50_0.1_0.25.metrics
    - models/metrics/10_25_0.1_0.25.metrics
