repos:
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
          - id: isort
            args: ["--filter-files"]
    - repo: https://github.com/psf/black
      rev: 23.10.1
      hooks:
          - id: black
            args: [--safe]
    - repo: https://github.com/PyCQA/flake8
      rev: 6.1.0
      hooks:
          - id: flake8
            args: ["--config=.flake8"]
            additional_dependencies: ['flake8-bugbear==23.9.16']
