channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.3.1
- pip:
  - mlflow==2.7.1
  - astunparse==1.6.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.6
  - numpy==1.23.5
  - opt-einsum==3.3.0
  - packaging==23.1
  - pandas==2.0.2
  - pydot==1.4.2
  - pyyaml==6.0
  - requests==2.31.0
  - scikit-image==0.21.0
  - scipy==1.10.1
  - torch==2.0.1
  - torchvision==0.15.2
  - tqdm==4.65.0
name: mlflow-env
