{
 "title": "Dashboard - CropSegmentation Copy",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Python Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "python_gc_objects_collected_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_gc_objects_uncollectable_total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "python_gc_collections_total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Scrape Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "scrape_duration_seconds",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "scrape_samples_post_metric_relabeling",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scrape_samples_post_metric_relabeling",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "scrape_samples_scraped",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "scrape_samples_scraped", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "scrape_series_added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "__auto" }
   ]
  },
  { "title": "Image Segmentation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Image Download Size Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "fastapi_model_image_download_size_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of HTTP Requests In Progress",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "fastapi_inprogress", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Number of Requests",
   "type": "barchart",
   "description": "Total number of requests made to FastAPI service.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(fastapi_model_total_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate of Image Segmentation",
   "type": "timeseries",
   "description": "Calculates the success rate of image segmentation as a percentage by analyzing the ratio of successfully segmented images to the total number of segmentation events. It uses the fastapi_model_segmentation_result_count metric, focusing on successful outcomes (result_type=\"success\"). The result is presented over a one-minute period, providing insights into the efficiency and performance of the image segmentation process.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(fastapi_model_segmentation_result_count{result_type=\"success\"}[1m]))\r\n  / \r\n  ignoring(result_type) group_left sum(rate(fastapi_model_segmentation_result_count[5m]))\r\n) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}