name: Data Drift Detection
run-name: Checking drift in data with Alibi

on:
  push:
    paths:
      - 'data/**'
      - 'src/**'
      - 'notebooks/6.1-agv-drift-with-alibi.ipynb'
      - 'tests/behavioral_testing/**'
      - 'tests/model_training_testing/**'

permissions:
  contents: write

jobs:
  drift-detection:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Set up DVC
      uses: iterative/setup-dvc@v1

    - name: Pull data with DVC
      env:
        GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      run: |
        dvc remote modify myremote gdrive_use_service_account true
        dvc pull -r myremote

    - name: Extract data
      run: |
        sudo apt-get install -y unzip
        unzip data/processed/datasets_processed.zip -d data/processed/datasets_processed

    - name: Data drift detection
      run: |
        python src/features/drift_detection.py

    - name: Upload log artifact
      uses: actions/upload-artifact@v3
      with:
        name: drift-detection
        path: log/drift-detection.log

    - name: Commit report
      run: |
        git status
        git config --global user.name "Gitty[bot]"
        git config --global user.email "Gitty[bot]@users.noreply.github.com"
        git commit -am "Automated drift detection logs"
        git push

    - name: Data Drift Detection - Debug mode
      run: |
        python src/features/drift_detection.py debug=1
