name: Testing Model

on:
  push:
    paths:
      - 'src/**'
      - '!src/api/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Set up Data
      run: |
        sudo apt-get install -y wget unzip
        . getdata.sh

    - name: Behavioral testing with pytest
      run: |
        cd tests/behavioral_testing
        pytest

    - name: Utility testing with pytest
      run: |
        cd ../tests/utility_testing
        pytest
