name: Testing API

on:
  push:
    paths:
      - src/api/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Activate virtual env
      run: |
        python -m pip install --upgrade pip
        python -m venv .env
        source .env/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    - name: Test with pytest
      run: |
        cd tests/api_testing
        pytest

    - name: Deactivate virtual env
      run: |
        deactivate
